-- MySQL Script generated by MySQL Workbench
-- Mon Feb 11 12:05:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KolejkaDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KolejkaDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KolejkaDb` DEFAULT CHARACTER SET utf8 ;
USE `KolejkaDb` ;

-- -----------------------------------------------------
-- Table `KolejkaDb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KolejkaDb`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `IndexNumber` VARCHAR(45) NOT NULL,
  `RFID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IndexNumber`),
  UNIQUE INDEX `idStudent_UNIQUE` (`idStudent` ASC) VISIBLE,
  UNIQUE INDEX `RFID_UNIQUE` (`RFID` ASC) VISIBLE,
  UNIQUE INDEX `IndexNumber_UNIQUE` (`IndexNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KolejkaDb`.`Field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KolejkaDb`.`Field` (
  `idField` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `isDaily` TINYINT NOT NULL,
  `isMaster` TINYINT NOT NULL,
  PRIMARY KEY (`idField`),
  UNIQUE INDEX `idField_UNIQUE` (`idField` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KolejkaDb`.`Field_has_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KolejkaDb`.`Field_has_Student` (
  `Field_idField` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`Field_idField`, `Student_idStudent`),
  INDEX `fk_Field_has_Student_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  INDEX `fk_Field_has_Student_Field_idx` (`Field_idField` ASC) VISIBLE,
  CONSTRAINT `fk_Field_has_Student_Field`
    FOREIGN KEY (`Field_idField`)
    REFERENCES `KolejkaDb`.`Field` (`idField`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Field_has_Student_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `KolejkaDb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KolejkaDb`.`Queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KolejkaDb`.`Queue` (
  `idQueue` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQueue`),
  UNIQUE INDEX `idQueue_UNIQUE` (`idQueue` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KolejkaDb`.`Queue_has_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KolejkaDb`.`Queue_has_Student` (
  `Queue_idQueue` INT NOT NULL,
  `Student_IndexNumber` VARCHAR(45) NOT NULL,
  `Data` DATETIME NOT NULL,
  PRIMARY KEY (`Queue_idQueue`, `Student_IndexNumber`),
  INDEX `fk_Queue_has_Student_Student1_idx` (`Student_IndexNumber` ASC) VISIBLE,
  INDEX `fk_Queue_has_Student_Queue1_idx` (`Queue_idQueue` ASC) VISIBLE,
  CONSTRAINT `fk_Queue_has_Student_Queue1`
    FOREIGN KEY (`Queue_idQueue`)
    REFERENCES `KolejkaDb`.`Queue` (`idQueue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Queue_has_Student_Student1`
    FOREIGN KEY (`Student_IndexNumber`)
    REFERENCES `KolejkaDb`.`Student` (`IndexNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
